<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<NeutralLanguage>uk-UA</NeutralLanguage>
		<IsTrimmable>true</IsTrimmable>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.7" />
		<PackageReference Include="Radzen.Blazor" Version="10.3.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AFS.Core\AFS.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Resource.Designer.cs">
		<DesignTime>True</DesignTime>
		<AutoGen>True</AutoGen>
		<DependentUpon>Resource.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<!-- Localization Resources - PUBLIC code generator for Resource.Designer.cs -->
	<ItemGroup>
		<EmbeddedResource Update="Resources\Resource.resx" Generator="PublicResXFileCodeGenerator" LastGenOutput="Resource.Designer.cs" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Update="Meziantou.Analyzer" Version="3.0.76" />
	  <PackageReference Update="SonarAnalyzer.CSharp" Version="10.25.0.139117" />
	</ItemGroup>

</Project>
