using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;

namespace AFS.Generators;

[Generator]
public class ResxLocalizationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var resxFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".resx", StringComparison.OrdinalIgnoreCase));
        var compilationAndFiles = context.CompilationProvider.Combine(resxFiles.Collect());
        context.RegisterSourceOutput(compilationAndFiles, (spc, source) =>
        {
            var (_, files) = source;
            GenerateLocalization(spc, files);
        });
    }

    private static void GenerateLocalization(SourceProductionContext context, ImmutableArray<AdditionalText> resxFiles)
    {
        if (resxFiles.IsDefaultOrEmpty) return;

        var cultureData = new Dictionary<string, Dictionary<string, string>>();
        foreach (var file in resxFiles.Where(f => 
            Path.GetFileName(f.Path).StartsWith("Resource", StringComparison.OrdinalIgnoreCase)))
        {
            var culture = GetCultureFromFileName(file.Path);
            var entries = ParseResxEntries(file);
            if (entries.Count > 0) cultureData[culture] = entries;
        }

        if (cultureData.Count == 0) return;
        context.AddSource("ChartLabels.g.cs", SourceText.From(GenerateClass(cultureData), Encoding.UTF8));
    }

    private static string GetCultureFromFileName(string path)
    {
        var fileName = Path.GetFileNameWithoutExtension(path);
        var dotIndex = fileName.IndexOf('.');
        return dotIndex > 0 ? fileName.Substring(dotIndex + 1) : "";
    }

    private static Dictionary<string, string> ParseResxEntries(AdditionalText file)
    {
        var entries = new Dictionary<string, string>();
        try
        {
            var text = file.GetText()?.ToString();
            if (string.IsNullOrEmpty(text)) return entries;
            var doc = XDocument.Parse(text);
            foreach (var el in doc.Descendants("data").Where(e => e.Attribute("name") != null))
            {
                var name = el.Attribute("name")?.Value;
                var value = el.Element("value")?.Value;
                if (!string.IsNullOrEmpty(name) && value != null) 
                    entries[name!] = value;
            }
        }
        catch { /* ignore parse errors */ }
        return entries;
    }

    private static string GenerateClass(Dictionary<string, Dictionary<string, string>> data)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine();
        sb.AppendLine("namespace AFS.ComponentLibrary.Resources;");
        sb.AppendLine();
        sb.AppendLine("public static class ChartLabels");
        sb.AppendLine("{");

        // Generate per-culture dictionaries
        foreach (var c in data.OrderBy(x => x.Key))
        {
            var n = string.IsNullOrEmpty(c.Key) ? "Invariant" : c.Key.Replace("-", "_");
            sb.AppendLine($"    private static readonly FrozenDictionary<string, string> _{n} = new Dictionary<string, string>");
            sb.AppendLine("    {");
            foreach (var e in c.Value.OrderBy(x => x.Key))
                sb.AppendLine($"        [\"{e.Key}\"] = \"{Escape(e.Value)}\",");
            sb.AppendLine("    }.ToFrozenDictionary(StringComparer.Ordinal);");
            sb.AppendLine();
        }

        // Generate cultures lookup
        sb.AppendLine("    private static readonly FrozenDictionary<string, FrozenDictionary<string, string>> _cultures = new Dictionary<string, FrozenDictionary<string, string>>");
        sb.AppendLine("    {");
        foreach (var c in data.OrderBy(x => x.Key))
        {
            var n = string.IsNullOrEmpty(c.Key) ? "Invariant" : c.Key.Replace("-", "_");
            sb.AppendLine($"        [\"{c.Key}\"] = _{n},");
        }
        sb.AppendLine("    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine();

        // Generate Get method
        sb.AppendLine("    public static string Get(string? key)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(key)) return \"Unknown\";");
        sb.AppendLine("        var culture = CultureInfo.CurrentUICulture;");
        sb.AppendLine("        if (_cultures.TryGetValue(culture.Name, out var d1) && d1.TryGetValue(key, out var v1)) return v1;");
        sb.AppendLine("        if (_cultures.TryGetValue(culture.TwoLetterISOLanguageName, out var d2) && d2.TryGetValue(key, out var v2)) return v2;");
        sb.AppendLine("        if (_cultures.TryGetValue(\"\", out var d3) && d3.TryGetValue(key, out var v3)) return v3;");
        sb.AppendLine("        return key;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Escape(string value) => 
        value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
}
