<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<!-- Performance Optimizations -->
		<BlazorEnableCompression>true</BlazorEnableCompression>
		
		<!-- Trimming Settings -->
		<PublishTrimmed>true</PublishTrimmed>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>full</TrimMode>
		
		<!-- AOT Settings -->
		<PublishAot>false</PublishAot>
		<IlcOptimizationPreference>Size</IlcOptimizationPreference>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
	</ItemGroup>

	<!-- Trimmer configuration to preserve ChartDataItem for Radzen reflection -->
	<ItemGroup>
		<TrimmerRootDescriptor Include="TrimmerRoots.xml" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Update="Meziantou.Analyzer" Version="3.0.19" />
	  <PackageReference Update="Roslynator.Analyzers" Version="4.15.0" />
	  <PackageReference Update="SonarAnalyzer.CSharp" Version="10.20.0.135146" />
	</ItemGroup>

</Project>
