// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "IL3050:Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation. Use System.Text.Json source generation for native AOT applications.", Justification = "<Pending>", Scope = "member", Target = "~M:AFS.Core.Services.BrowserExportImportHandler.ExportAsync(AFS.Core.Models.AFSModel)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "IL2026:Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.", Justification = "<Pending>", Scope = "member", Target = "~M:AFS.Core.Services.BrowserExportImportHandler.ExportAsync(AFS.Core.Models.AFSModel)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "IL2026:Using member 'System.Text.Json.JsonSerializer.DeserializeAsync<TValue>(Stream, JsonSerializerOptions, CancellationToken)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.", Justification = "<Pending>", Scope = "member", Target = "~M:AFS.Core.Services.BrowserExportImportHandler.ImportAsync(System.IO.Stream)~System.Threading.Tasks.Task{AFS.Core.Models.AFSModel}")]
[assembly: SuppressMessage("Build", "IL3050:Using member 'System.Text.Json.JsonSerializer.DeserializeAsync<TValue>(Stream, JsonSerializerOptions, CancellationToken)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation. Use System.Text.Json source generation for native AOT applications.", Justification = "<Pending>", Scope = "member", Target = "~M:AFS.Core.Services.BrowserExportImportHandler.ImportAsync(System.IO.Stream)~System.Threading.Tasks.Task{AFS.Core.Models.AFSModel}")]
[assembly: SuppressMessage("Build", "IL3050:Using member 'System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsync<TValue>(HttpClient, String, CancellationToken)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext.", Justification = "<Pending>", Scope = "member", Target = "~M:AFS.Core.Services.LocalStorageModelHandler.ReadModelAsync~System.Threading.Tasks.Task{AFS.Core.Models.AFSModel}")]
[assembly: SuppressMessage("Build", "IL2026:Using member 'System.Text.Json.JsonSerializer.Deserialize<TValue>(String, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.", Justification = "<Pending>", Scope = "member", Target = "~M:AFS.Core.Services.LocalStorageModelHandler.ReadModelAsync~System.Threading.Tasks.Task{AFS.Core.Models.AFSModel}")]
[assembly: SuppressMessage("Build", "IL2026:Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.", Justification = "<Pending>", Scope = "member", Target = "~M:AFS.Core.Services.LocalStorageModelHandler.WriteModelAsync(AFS.Core.Models.AFSModel)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "IL3050:Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation. Use System.Text.Json source generation for native AOT applications.", Justification = "<Pending>", Scope = "member", Target = "~M:AFS.Core.Services.LocalStorageModelHandler.WriteModelAsync(AFS.Core.Models.AFSModel)~System.Threading.Tasks.Task")]
