//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFS.ComponentLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AFS.ComponentLibrary.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дебіторська заборгованість.
        /// </summary>
        internal static string AccountsReceivable {
            get {
                return ResourceManager.GetString("AccountsReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дебіторська заборгованість за розрахунками.
        /// </summary>
        internal static string AccountsReceivableForDebts {
            get {
                return ResourceManager.GetString("AccountsReceivableForDebts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума нарахованого зносу на початок року.
        /// </summary>
        internal static string AccruedDepreciationAtBegin {
            get {
                return ResourceManager.GetString("AccruedDepreciationAtBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума нарахованого зносу на кінець року.
        /// </summary>
        internal static string AccruedDepreciationAtEnd {
            get {
                return ResourceManager.GetString("AccruedDepreciationAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to накопичена амортизація.
        /// </summary>
        internal static string accumulatedDepreciation {
            get {
                return ResourceManager.GetString("accumulatedDepreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Накопичені курсові різниці.
        /// </summary>
        internal static string AccumulatedExchangeRateDifferences {
            get {
                return ResourceManager.GetString("AccumulatedExchangeRateDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатковий капітал.
        /// </summary>
        internal static string AdditionalCapital {
            get {
                return ResourceManager.GetString("AdditionalCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додаткова інформація.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоригована середньорічна кількість простих акцій.
        /// </summary>
        internal static string AdjustedAverageNumberOrdinaryShares {
            get {
                return ResourceManager.GetString("AdjustedAverageNumberOrdinaryShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to скоригований показник.
        /// </summary>
        internal static string adjustedIndicator {
            get {
                return ResourceManager.GetString("adjustedIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоригований чистий прибуток (збиток) на одну просту акцію.
        /// </summary>
        internal static string AdjustedNetProfitLossPerOrdinaryShare {
            get {
                return ResourceManager.GetString("AdjustedNetProfitLossPerOrdinaryShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адміністративні витрати.
        /// </summary>
        internal static string AdministrativeExpenses {
            get {
                return ResourceManager.GetString("AdministrativeExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амортизація.
        /// </summary>
        internal static string Amortization {
            get {
                return ResourceManager.GetString("Amortization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стаття.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцінка фінансової звітності.
        /// </summary>
        internal static string AssessmentOfFinancialStatements {
            get {
                return ResourceManager.GetString("AssessmentOfFinancialStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актив.
        /// </summary>
        internal static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На початок звітного періоду.
        /// </summary>
        internal static string AtBeginningReportingPeriod {
            get {
                return ResourceManager.GetString("AtBeginningReportingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на початок року.
        /// </summary>
        internal static string atBeginOfYear {
            get {
                return ResourceManager.GetString("atBeginOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На кінець звітного періоду.
        /// </summary>
        internal static string AtEndingReportingPeriod {
            get {
                return ResourceManager.GetString("AtEndingReportingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на кінець року.
        /// </summary>
        internal static string atEndOfYear {
            get {
                return ResourceManager.GetString("atEndOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наявність та рух основних засобів.
        /// </summary>
        internal static string AvailabilityAndMovementOfFixedAssets {
            get {
                return ResourceManager.GetString("AvailabilityAndMovementOfFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середньорічна вартість основних засобів.
        /// </summary>
        internal static string AverageAnnualCostOfFixedAssets {
            get {
                return ResourceManager.GetString("AverageAnnualCostOfFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середньорічна вартість нематеріальних активів.
        /// </summary>
        internal static string AverageAnnualCostOfIntangibleAssets {
            get {
                return ResourceManager.GetString("AverageAnnualCostOfIntangibleAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to середніх залишків.
        /// </summary>
        internal static string averageBalances {
            get {
                return ResourceManager.GetString("averageBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середньоспискова чисельність працівників.
        /// </summary>
        internal static string AverageNumberOfEmployees {
            get {
                return ResourceManager.GetString("AverageNumberOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середньорічна кількість простих акцій.
        /// </summary>
        internal static string AverageNumberOrdinaryShares {
            get {
                return ResourceManager.GetString("AverageNumberOrdinaryShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середні залишки оборотних засобів.
        /// </summary>
        internal static string AverageWorkingCapitalBalances {
            get {
                return ResourceManager.GetString("AverageWorkingCapitalBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залишок на початок року за первісною вартістю.
        /// </summary>
        internal static string BalanceAtBeginOfYearAtOriginalCost {
            get {
                return ResourceManager.GetString("BalanceAtBeginOfYearAtOriginalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залишок на кінець року за первісною вартістю.
        /// </summary>
        internal static string BalanceAtEndOfYearAtOriginalBalanceAtEndOfYearAtOriginalCost {
            get {
                return ResourceManager.GetString("BalanceAtEndOfYearAtOriginalBalanceAtEndOfYearAtOriginalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залишок на кінець року за мінусом зносу.
        /// </summary>
        internal static string BalanceAtEndOfYearMinusDepreciation {
            get {
                return ResourceManager.GetString("BalanceAtEndOfYearMinusDepreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовий рік.
        /// </summary>
        internal static string BaseYear {
            get {
                return ResourceManager.GetString("BaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за розрахунками з учасниками.
        /// </summary>
        internal static string bySettlementsWithParticipants {
            get {
                return ResourceManager.GetString("bySettlementsWithParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розрахунок узагальнюючих показників ефективності використання основних засобів.
        /// </summary>
        internal static string CalculationOfIndicatorsOfEfficiencyOfUseOfFixedAssets {
            get {
                return ResourceManager.GetString("CalculationOfIndicatorsOfEfficiencyOfUseOfFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця {0}. Розрахунок узагальнюючих показників ефективності використання основних засобів {1} за {2}-{3} роки.
        /// </summary>
        internal static string CalculationOfIndicatorsOfEfficiencyOfUseOfFixedAssetsTablName {
            get {
                return ResourceManager.GetString("CalculationOfIndicatorsOfEfficiencyOfUseOfFixedAssetsTablName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розрахунок показників прибутковості акцій.
        /// </summary>
        internal static string CalculationStockProfitabilityIndicators {
            get {
                return ResourceManager.GetString("CalculationStockProfitabilityIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Капітал у дооцінках.
        /// </summary>
        internal static string CapitalInRevaluations {
            get {
                return ResourceManager.GetString("CapitalInRevaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фондоємкість продукції.
        /// </summary>
        internal static string CapitalIntensityOfProducts {
            get {
                return ResourceManager.GetString("CapitalIntensityOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to товари.
        /// </summary>
        internal static string cargo {
            get {
                return ResourceManager.GetString("cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грошові засоби і поточні фінансові інвестиції.
        /// </summary>
        internal static string CashCurrentFinancialInvestments {
            get {
                return ResourceManager.GetString("CashCurrentFinancialInvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика капіталу.
        /// </summary>
        internal static string CharacteristicsOfCapital {
            get {
                return ResourceManager.GetString("CharacteristicsOfCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва компанії.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сукупний дохід.
        /// </summary>
        internal static string ComprehensiveIncome {
            get {
                return ResourceManager.GetString("ComprehensiveIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собівартість реалізованої продукції (товарів, робіт, послуг).
        /// </summary>
        internal static string CostOfGoodsSold {
            get {
                return ResourceManager.GetString("CostOfGoodsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість вибулих основних фондів.
        /// </summary>
        internal static string CostOfLeftFixedAssets {
            get {
                return ResourceManager.GetString("CostOfLeftFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грн..
        /// </summary>
        internal static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточна кредиторська заборгованість за.
        /// </summary>
        internal static string CurrentAccountsPayableFor {
            get {
                return ResourceManager.GetString("CurrentAccountsPayableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оборотні активи.
        /// </summary>
        internal static string CurrentAssets {
            get {
                return ResourceManager.GetString("CurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточні біологічні активи.
        /// </summary>
        internal static string CurrentBiologicalAssets {
            get {
                return ResourceManager.GetString("CurrentBiologicalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточні фінансові інвестиції.
        /// </summary>
        internal static string CurrentFinancialInvestments {
            get {
                return ResourceManager.GetString("CurrentFinancialInvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточні зобов&apos;язання і забезпечення.
        /// </summary>
        internal static string CurrentLiabilitiesAndProvisions {
            get {
                return ResourceManager.GetString("CurrentLiabilitiesAndProvisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оборотні (мобільні) засоби.
        /// </summary>
        internal static string CurrentMobileAssets {
            get {
                return ResourceManager.GetString("CurrentMobileAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточні забезпечення.
        /// </summary>
        internal static string CurrentSupplies {
            get {
                return ResourceManager.GetString("CurrentSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточний рік.
        /// </summary>
        internal static string CurrentYear {
            get {
                return ResourceManager.GetString("CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to днів.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відрахування на соціальні заходи.
        /// </summary>
        internal static string DeductionsSocialEvents {
            get {
                return ResourceManager.GetString("DeductionsSocialEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відстрочені податкові зобов&apos;язання.
        /// </summary>
        internal static string DeferredTaxLiabilities {
            get {
                return ResourceManager.GetString("DeferredTaxLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коефіцієнт зносу основних засобів на початок року.
        /// </summary>
        internal static string DepreciationRateOfFixedAssetAtBegin {
            get {
                return ResourceManager.GetString("DepreciationRateOfFixedAssetAtBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коефіцієнт зносу основних засобів на кінець року.
        /// </summary>
        internal static string DepreciationRateOfFixedAssetAtEnd {
            get {
                return ResourceManager.GetString("DepreciationRateOfFixedAssetAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to відхилення.
        /// </summary>
        internal static string deviation {
            get {
                return ResourceManager.GetString("deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відхилення.
        /// </summary>
        internal static string Deviation_ {
            get {
                return ResourceManager.GetString("Deviation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коефіцієнт вибуття.
        /// </summary>
        internal static string DisposalRate {
            get {
                return ResourceManager.GetString("DisposalRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дивіденди на одну просту акцію.
        /// </summary>
        internal static string DividendsPerSimpleShare {
            get {
                return ResourceManager.GetString("DividendsPerSimpleShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Динаміка.
        /// </summary>
        internal static string Dynamics {
            get {
                return ResourceManager.GetString("Dynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Елементи операційних витрат.
        /// </summary>
        internal static string ElementsOperatingCosts {
            get {
                return ResourceManager.GetString("ElementsOperatingCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Власний капітал.
        /// </summary>
        internal static string Equity {
            get {
                return ResourceManager.GetString("Equity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стерти дані.
        /// </summary>
        internal static string EraseData {
            get {
                return ResourceManager.GetString("EraseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрати (дохід) з податку на прибуток.
        /// </summary>
        internal static string ExpensesIncomeFromIncomeTax {
            get {
                return ResourceManager.GetString("ExpensesIncomeFromIncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факторний аналіз фондовіддачі основних засобів.
        /// </summary>
        internal static string FactorAnalysisOfFixedAssets {
            get {
                return ResourceManager.GetString("FactorAnalysisOfFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактори, що впливають на оборотність оборотних засобів.
        /// </summary>
        internal static string FactorsAffectingTurnoverOfWorkingCapital {
            get {
                return ResourceManager.GetString("FactorsAffectingTurnoverOfWorkingCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінансові витрати.
        /// </summary>
        internal static string FinancialExpenses {
            get {
                return ResourceManager.GetString("FinancialExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінансовий результат до оподаткування.
        /// </summary>
        internal static string FinancialResultBeforeTax {
            get {
                return ResourceManager.GetString("FinancialResultBeforeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінансовий результат від операційної діяльності.
        /// </summary>
        internal static string FinancialResultFromOperatingActivities {
            get {
                return ResourceManager.GetString("FinancialResultFromOperatingActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінансові результати.
        /// </summary>
        internal static string FinancialResults {
            get {
                return ResourceManager.GetString("FinancialResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to готова продукція.
        /// </summary>
        internal static string finishedProducts {
            get {
                return ResourceManager.GetString("finishedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основні засоби.
        /// </summary>
        internal static string FixedAssets {
            get {
                return ResourceManager.GetString("FixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коефіцієнт закріплення оборотних засобів.
        /// </summary>
        internal static string FixingRatioOfCurrentAssets {
            get {
                return ResourceManager.GetString("FixingRatioOfCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За звітний період.
        /// </summary>
        internal static string ForReportingPeriod {
            get {
                return ResourceManager.GetString("ForReportingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За аналогічний період попереднього року.
        /// </summary>
        internal static string ForSamePeriodLastYear {
            get {
                return ResourceManager.GetString("ForSamePeriodLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to з нарахованих доходів.
        /// </summary>
        internal static string fromAccruedIncome {
            get {
                return ResourceManager.GetString("fromAccruedIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to із внутрішніх розрахунків.
        /// </summary>
        internal static string fromInternalSettlements {
            get {
                return ResourceManager.GetString("fromInternalSettlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грошових коштів.
        /// </summary>
        internal static string fromMoney {
            get {
                return ResourceManager.GetString("fromMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дебіторської заборгованості.
        /// </summary>
        internal static string fromReceivables {
            get {
                return ResourceManager.GetString("fromReceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to матеріальних цінностей.
        /// </summary>
        internal static string fromTangibleAssets {
            get {
                return ResourceManager.GetString("fromTangibleAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрати майбутніх періодів.
        /// </summary>
        internal static string FutureExpenses {
            get {
                return ResourceManager.GetString("FutureExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доходи майбутніх періодів.
        /// </summary>
        internal static string FutureIncome {
            get {
                return ResourceManager.GetString("FutureIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна інформація.
        /// </summary>
        internal static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to товари, роботи, послуги.
        /// </summary>
        internal static string goodsWorksServices {
            get {
                return ResourceManager.GetString("goodsWorksServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валовий.
        /// </summary>
        internal static string Gross {
            get {
                return ResourceManager.GetString("Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to темп роста.
        /// </summary>
        internal static string growthRate {
            get {
                return ResourceManager.GetString("growthRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в %  до оборотних засобів.
        /// </summary>
        internal static string in_toCurrentMobileAssets {
            get {
                return ResourceManager.GetString("in%toCurrentMobileAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to у тому числі за рахунок.
        /// </summary>
        internal static string includingDueTo {
            get {
                return ResourceManager.GetString("includingDueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to у т.ч.  ліквідовано.
        /// </summary>
        internal static string includingEliminated {
            get {
                return ResourceManager.GetString("includingEliminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to у тому числі з податку на прибуток.
        /// </summary>
        internal static string includingIncomeTax {
            get {
                return ResourceManager.GetString("includingIncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to у т.ч. нові.
        /// </summary>
        internal static string includingNew {
            get {
                return ResourceManager.GetString("includingNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дохід від участі в капіталі.
        /// </summary>
        internal static string IncomeFromEquityParticipation {
            get {
                return ResourceManager.GetString("IncomeFromEquityParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Податок на прибуток, пов’язаний з іншим сукупним доходом.
        /// </summary>
        internal static string IncomeTaxRelatedOtherComprehensiveIncome {
            get {
                return ResourceManager.GetString("IncomeTaxRelatedOtherComprehensiveIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Незавершені капітальні інвестиції.
        /// </summary>
        internal static string IncompleteCapitalInvestments {
            get {
                return ResourceManager.GetString("IncompleteCapitalInvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показники.
        /// </summary>
        internal static string Indicators {
            get {
                return ResourceManager.GetString("Indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показники ефективності використання нематеріальних активів.
        /// </summary>
        internal static string IndicatorsOfEfficiencyOfUseOfIntangibleAssets {
            get {
                return ResourceManager.GetString("IndicatorsOfEfficiencyOfUseOfIntangibleAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показники ефективності використання оборотних засобів.
        /// </summary>
        internal static string IndicatorsOfEfficiencyOfWorkingCapital {
            get {
                return ResourceManager.GetString("IndicatorsOfEfficiencyOfWorkingCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показники стану та руху основних засобів.
        /// </summary>
        internal static string IndicatorsOfStateAndMovementOfFixedAssets {
            get {
                return ResourceManager.GetString("IndicatorsOfStateAndMovementOfFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показники оборотності оборотних засобів.
        /// </summary>
        internal static string IndicatorsOfTurnoverOfCurrentAssets {
            get {
                return ResourceManager.GetString("IndicatorsOfTurnoverOfCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to первісна вартість.
        /// </summary>
        internal static string initialCost {
            get {
                return ResourceManager.GetString("initialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первісна вартість основних засобів на початок періоду.
        /// </summary>
        internal static string InitialCostOfFixedAssetsAtBegin {
            get {
                return ResourceManager.GetString("InitialCostOfFixedAssetsAtBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первісна вартість основних засобів на кінець періоду.
        /// </summary>
        internal static string InitialCostOfFixedAssetsAtEndOfPeriod {
            get {
                return ResourceManager.GetString("InitialCostOfFixedAssetsAtEndOfPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхідні дані.
        /// </summary>
        internal static string InputData {
            get {
                return ResourceManager.GetString("InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нематеріальні активи.
        /// </summary>
        internal static string IntangibleAssets {
            get {
                return ResourceManager.GetString("IntangibleAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інтегральний показник ефективності використання оборотних засобів.
        /// </summary>
        internal static string IntegratedIndicatorOfEfficiencyOfCurrentAssets {
            get {
                return ResourceManager.GetString("IntegratedIndicatorOfEfficiencyOfCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інтегральний показник ефективності використання основних засобів.
        /// </summary>
        internal static string IntegratedIndicatorOnFixedAssets {
            get {
                return ResourceManager.GetString("IntegratedIndicatorOnFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інвестиційна нерухомість.
        /// </summary>
        internal static string InvestmentProperty {
            get {
                return ResourceManager.GetString("InvestmentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фондоозброєність праці одного середньоспискового працівника.
        /// </summary>
        internal static string LaborCapitalOfOneAverageEmployee {
            get {
                return ResourceManager.GetString("LaborCapitalOfOneAverageEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пасив.
        /// </summary>
        internal static string Liabilities {
            get {
                return ResourceManager.GetString("Liabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зобов&apos;язання, пов&apos;язані з необоротними активами утримуваними для продажу, та групами вибуття.
        /// </summary>
        internal static string LiabilitiesRelatedNonCurrentAssetsHeldForSale {
            get {
                return ResourceManager.GetString("LiabilitiesRelatedNonCurrentAssetsHeldForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код рядка.
        /// </summary>
        internal static string LineСode {
            get {
                return ResourceManager.GetString("LineСode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові кредити банків.
        /// </summary>
        internal static string LongTermBankCredits {
            get {
                return ResourceManager.GetString("LongTermBankCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові біологічні активи.
        /// </summary>
        internal static string LongTermBiologicalAssets {
            get {
                return ResourceManager.GetString("LongTermBiologicalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові фінансові інвестиції.
        /// </summary>
        internal static string LongTermFinancialIvestments {
            get {
                return ResourceManager.GetString("LongTermFinancialIvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to довгостроковими зобов&apos;язаннями.
        /// </summary>
        internal static string longTermLiabilities {
            get {
                return ResourceManager.GetString("longTermLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові зобов&apos;язання і забезпечення.
        /// </summary>
        internal static string LongTermLiabilitiesAndCollateral {
            get {
                return ResourceManager.GetString("LongTermLiabilitiesAndCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові забезпечення.
        /// </summary>
        internal static string LongTermLoans {
            get {
                return ResourceManager.GetString("LongTermLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокова дебіторська заборгованість.
        /// </summary>
        internal static string LongTermReceivables {
            get {
                return ResourceManager.GetString("LongTermReceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to збиток.
        /// </summary>
        internal static string loss {
            get {
                return ResourceManager.GetString("loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Втрати від участі в капіталі.
        /// </summary>
        internal static string LossesFromEquityParticipation {
            get {
                return ResourceManager.GetString("LossesFromEquityParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матеріальні затрати.
        /// </summary>
        internal static string MaterialCosts {
            get {
                return ResourceManager.GetString("MaterialCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оборотність матеріальних цінностей.
        /// </summary>
        internal static string materialValuesTurnover {
            get {
                return ResourceManager.GetString("materialValuesTurnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гроші та їх еквіваленти.
        /// </summary>
        internal static string MoneyAndTheirEquivalents {
            get {
                return ResourceManager.GetString("MoneyAndTheirEquivalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оборотність грошових коштів.
        /// </summary>
        internal static string moneyTurnover {
            get {
                return ResourceManager.GetString("moneyTurnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистий фінансовий результат.
        /// </summary>
        internal static string NetFinancialResult {
            get {
                return ResourceManager.GetString("NetFinancialResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистий доход (виручка) від реалізації.
        /// </summary>
        internal static string NetIncomeFromSales {
            get {
                return ResourceManager.GetString("NetIncomeFromSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистий дохід від реалізації продукції (товарів, робіт, послуг).
        /// </summary>
        internal static string NetIncomeFromSalesOfProducts {
            get {
                return ResourceManager.GetString("NetIncomeFromSalesOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистий прибуток.
        /// </summary>
        internal static string NetProfit {
            get {
                return ResourceManager.GetString("NetProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистий прибуток (збиток) на одну просту акцію.
        /// </summary>
        internal static string NetProfitLossPerOrdinaryShare {
            get {
                return ResourceManager.GetString("NetProfitLossPerOrdinaryShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необоротні активи.
        /// </summary>
        internal static string NonCurrentAssets {
            get {
                return ResourceManager.GetString("NonCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необоротні активи, утримувані для продажу, та групи вибуття.
        /// </summary>
        internal static string NonCurrentAssetsHeldForSale {
            get {
                return ResourceManager.GetString("NonCurrentAssetsHeldForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необоротні (імобілізовані) засоби.
        /// </summary>
        internal static string NonCurrentImmobilizedAssets {
            get {
                return ResourceManager.GetString("NonCurrentImmobilizedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № п/п.
        /// </summary>
        internal static string NumberInOrder {
            get {
                return ResourceManager.GetString("NumberInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість оборотів оборотних засобів.
        /// </summary>
        internal static string NumberOfRevolutionsOfCurrentAssets {
            get {
                return ResourceManager.GetString("NumberOfRevolutionsOfCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одноденна виручка від реалізації.
        /// </summary>
        internal static string OneDaySalesRevenue {
            get {
                return ResourceManager.GetString("OneDaySalesRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за виданими авансами.
        /// </summary>
        internal static string onIssuedAdvances {
            get {
                return ResourceManager.GetString("onIssuedAdvances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за одержаними авансами.
        /// </summary>
        internal static string onReceivedAdvances {
            get {
                return ResourceManager.GetString("onReceivedAdvances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інший сукупний дохід після оподаткування.
        /// </summary>
        internal static string OtherAggregateIncomeAfterTax {
            get {
                return ResourceManager.GetString("OtherAggregateIncomeAfterTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інший сукупний дохід до оподаткування.
        /// </summary>
        internal static string OtherAggregatePreTaxIncome {
            get {
                return ResourceManager.GetString("OtherAggregatePreTaxIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші оборотні активи.
        /// </summary>
        internal static string OtherCurrentAssets {
            get {
                return ResourceManager.GetString("OtherCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші поточні зобов&apos;язання.
        /// </summary>
        internal static string OtherCurrentLiabilities {
            get {
                return ResourceManager.GetString("OtherCurrentLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інша поточна дебіторська заборгованість.
        /// </summary>
        internal static string OtherCurrentReceivables {
            get {
                return ResourceManager.GetString("OtherCurrentReceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші витрати.
        /// </summary>
        internal static string OtherExpenses {
            get {
                return ResourceManager.GetString("OtherExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші фінансові доходи.
        /// </summary>
        internal static string OtherFinancialIncome {
            get {
                return ResourceManager.GetString("OtherFinancialIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to інші фінансові інвестиції.
        /// </summary>
        internal static string otherFinancialInvestments {
            get {
                return ResourceManager.GetString("otherFinancialInvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші необоротні активи.
        /// </summary>
        internal static string OtherFixedAssets {
            get {
                return ResourceManager.GetString("OtherFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші доходи.
        /// </summary>
        internal static string OtherIncome {
            get {
                return ResourceManager.GetString("OtherIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші довгострокові зобов&apos;язання.
        /// </summary>
        internal static string OtherLongTermLiabilities {
            get {
                return ResourceManager.GetString("OtherLongTermLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші операційні витрати.
        /// </summary>
        internal static string OtherOperatingExpenses {
            get {
                return ResourceManager.GetString("OtherOperatingExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші операційні доходи.
        /// </summary>
        internal static string OtherOperatingIncome {
            get {
                return ResourceManager.GetString("OtherOperatingIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інший сукупний дохід.
        /// </summary>
        internal static string OtherTotalIncome {
            get {
                return ResourceManager.GetString("OtherTotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to чол..
        /// </summary>
        internal static string people {
            get {
                return ResourceManager.GetString("people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Період.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відстрочені податкові активи.
        /// </summary>
        internal static string PostponedTaxAssets {
            get {
                return ResourceManager.GetString("PostponedTaxAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виручка від реалізації продукції.
        /// </summary>
        internal static string ProceedsFromSales {
            get {
                return ResourceManager.GetString("ProceedsFromSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to виробничі запаси.
        /// </summary>
        internal static string productionStocks {
            get {
                return ResourceManager.GetString("productionStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продуктивність праці одного середньоспискового працівника.
        /// </summary>
        internal static string ProductivityOfOneAverageEmployee {
            get {
                return ResourceManager.GetString("ProductivityOfOneAverageEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to прибуток.
        /// </summary>
        internal static string profit {
            get {
                return ResourceManager.GetString("profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рентабельність оборотних засобів.
        /// </summary>
        internal static string ProfitabilityOfCurrentAssets {
            get {
                return ResourceManager.GetString("ProfitabilityOfCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рентабельність основних засобів.
        /// </summary>
        internal static string ProfitabilityOnFixedAssets {
            get {
                return ResourceManager.GetString("ProfitabilityOnFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибуток від операційної діяльності.
        /// </summary>
        internal static string ProfitFromOperatingActivities {
            get {
                return ResourceManager.GetString("ProfitFromOperatingActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибуток (збиток) від припиненої діяльності після оподаткування.
        /// </summary>
        internal static string ProfitLossFromDiscontinuedOperationsAfterTax {
            get {
                return ResourceManager.GetString("ProfitLossFromDiscontinuedOperationsAfterTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Векселі видані.
        /// </summary>
        internal static string PromissoryNotesIssued {
            get {
                return ResourceManager.GetString("PromissoryNotesIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Векселі одержані.
        /// </summary>
        internal static string PromissoryNotesReceived {
            get {
                return ResourceManager.GetString("PromissoryNotesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дебіторська заборгованість за продукцію, товари, роботи, послуги.
        /// </summary>
        internal static string ReceivablesForProducts {
            get {
                return ResourceManager.GetString("ReceivablesForProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оборотність дебіторської заборгованості.
        /// </summary>
        internal static string receivablesTurnover {
            get {
                return ResourceManager.GetString("receivablesTurnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надійшло основні засоби.
        /// </summary>
        internal static string ReceivedFixedAssets {
            get {
                return ResourceManager.GetString("ReceivedFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надійшло за звітний період.
        /// </summary>
        internal static string ReceivedForReportingPeriod {
            get {
                return ResourceManager.GetString("ReceivedForReportingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коефіцієнт відновлення.
        /// </summary>
        internal static string RecoveryRate {
            get {
                return ResourceManager.GetString("RecoveryRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєстрований (пайовий) капітал.
        /// </summary>
        internal static string RegisteredСapital {
            get {
                return ResourceManager.GetString("RegisteredСapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звільнення (-), відсутність оборотних активів (+) через зміну їх оборотності.
        /// </summary>
        internal static string ReleaseOrLackOfCurrentAssetsDueTurnover {
            get {
                return ResourceManager.GetString("ReleaseOrLackOfCurrentAssetsDueTurnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервний капітал.
        /// </summary>
        internal static string ReserveCapital {
            get {
                return ResourceManager.GetString("ReserveCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нерозподілений прибуток (непокритий збиток).
        /// </summary>
        internal static string RetainedEarnings {
            get {
                return ResourceManager.GetString("RetainedEarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виведені з експлуатації основні засоби.
        /// </summary>
        internal static string RetiredFixedAssets {
            get {
                return ResourceManager.GetString("RetiredFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фондовіддача основних засобів.
        /// </summary>
        internal static string ReturnOnFixedAssets {
            get {
                return ResourceManager.GetString("ReturnOnFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фондовіддача нематеріальних активів.
        /// </summary>
        internal static string ReturnOnIntangibleAssets {
            get {
                return ResourceManager.GetString("ReturnOnIntangibleAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дооцінка (уцінка) фінансових інструментів.
        /// </summary>
        internal static string RevaluationDepreciationFinancialInstruments {
            get {
                return ResourceManager.GetString("RevaluationDepreciationFinancialInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дооцінка (уцінка) необоротних активів.
        /// </summary>
        internal static string RevaluationDepreciationNonCurrentAssets {
            get {
                return ResourceManager.GetString("RevaluationDepreciationNonCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to виручки.
        /// </summary>
        internal static string revenue {
            get {
                return ResourceManager.GetString("revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрати на оплату праці.
        /// </summary>
        internal static string SalaryExpenses {
            get {
                return ResourceManager.GetString("SalaryExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to То же в % до активів.
        /// </summary>
        internal static string Samein_OfAssets {
            get {
                return ResourceManager.GetString("Samein%OfAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти у файл.
        /// </summary>
        internal static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрати на збут.
        /// </summary>
        internal static string SellingExpenses {
            get {
                return ResourceManager.GetString("SellingExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to розрахунками з бюджетом.
        /// </summary>
        internal static string settlementsWithBudget {
            get {
                return ResourceManager.GetString("settlementsWithBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to розрахунками зі страхування.
        /// </summary>
        internal static string settlementsWithInsurance {
            get {
                return ResourceManager.GetString("settlementsWithInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to розрахунками з оплати праці.
        /// </summary>
        internal static string settlementsWithPayroll {
            get {
                return ResourceManager.GetString("settlementsWithPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частка іншого сукупного доходу асоційованих та спільних підприємств.
        /// </summary>
        internal static string ShareOtherComprehensiveIncome {
            get {
                return ResourceManager.GetString("ShareOtherComprehensiveIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткострокові кредити банків.
        /// </summary>
        internal static string ShortTermBankCredits {
            get {
                return ResourceManager.GetString("ShortTermBankCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звіт про фінансові результати (Звіт про сукупний дохід).
        /// </summary>
        internal static string StatementOfFinancialPerformance {
            get {
                return ResourceManager.GetString("StatementOfFinancialPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запаси.
        /// </summary>
        internal static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коефіцієнт придатності на початок року.
        /// </summary>
        internal static string SuitabilityRatioForBegin {
            get {
                return ResourceManager.GetString("SuitabilityRatioForBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коефіцієнт придатності на кінець року.
        /// </summary>
        internal static string SuitabilityRatioForEnd {
            get {
                return ResourceManager.GetString("SuitabilityRatioForEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матеріальні оборотні засоби.
        /// </summary>
        internal static string TangibleCurrentAssets {
            get {
                return ResourceManager.GetString("TangibleCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матеріальні цінності.
        /// </summary>
        internal static string Tangibles {
            get {
                return ResourceManager.GetString("Tangibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цільове фінансування.
        /// </summary>
        internal static string TargetedFinancing {
            get {
                return ResourceManager.GetString("TargetedFinancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість уведених в дію нових основних фондів.
        /// </summary>
        internal static string TheCostOfNewFixedAssets {
            get {
                return ResourceManager.GetString("TheCostOfNewFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тис.грн..
        /// </summary>
        internal static string thousandUAH {
            get {
                return ResourceManager.GetString("thousandUAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to раз.
        /// </summary>
        internal static string times {
            get {
                return ResourceManager.GetString("times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разом.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to усього.
        /// </summary>
        internal static string total_ {
            get {
                return ResourceManager.GetString("total_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усього капіталу (активів).
        /// </summary>
        internal static string TotalAssets {
            get {
                return ResourceManager.GetString("TotalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сукупний дохід.
        /// </summary>
        internal static string TotalIncome {
            get {
                return ResourceManager.GetString("TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усього за розділом.
        /// </summary>
        internal static string TotalSection {
            get {
                return ResourceManager.GetString("TotalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усього оборотних засобів.
        /// </summary>
        internal static string TotalWorkingCapital {
            get {
                return ResourceManager.GetString("TotalWorkingCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оборотність.
        /// </summary>
        internal static string Turnover {
            get {
                return ResourceManager.GetString("Turnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оборотність оборотних засобів.
        /// </summary>
        internal static string TurnoverOfCurrentAssets {
            get {
                return ResourceManager.GetString("TurnoverOfCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оборотність оборотних засобів.
        /// </summary>
        internal static string TurnoverOfWorkingCapital {
            get {
                return ResourceManager.GetString("TurnoverOfWorkingCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Види оборотних засобів.
        /// </summary>
        internal static string TypesOfCurrentAssets {
            get {
                return ResourceManager.GetString("TypesOfCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to незавершене виробництво.
        /// </summary>
        internal static string unfinishedProduction {
            get {
                return ResourceManager.GetString("unfinishedProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неоплачений капітал.
        /// </summary>
        internal static string UnpaidCapital {
            get {
                return ResourceManager.GetString("UnpaidCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити з файлу.
        /// </summary>
        internal static string UploadFromFile {
            get {
                return ResourceManager.GetString("UploadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to знос.
        /// </summary>
        internal static string wear {
            get {
                return ResourceManager.GetString("wear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to які обліковуються за методом участі в капіталі інших підприємств.
        /// </summary>
        internal static string whichAccountedForUsingEquityMethod {
            get {
                return ResourceManager.GetString("whichAccountedForUsingEquityMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to з бюджетом.
        /// </summary>
        internal static string withBudget {
            get {
                return ResourceManager.GetString("withBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вилучений капітал.
        /// </summary>
        internal static string WithdrawnCapital {
            get {
                return ResourceManager.GetString("WithdrawnCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибуло в звітному періоді.
        /// </summary>
        internal static string WithdrewInReportingPeriod {
            get {
                return ResourceManager.GetString("WithdrewInReportingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рік.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to роки.
        /// </summary>
        internal static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
