//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFS.ComponentLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AFS.ComponentLibrary.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дебіторська заборгованість за розрахунками.
        /// </summary>
        internal static string AccountsReceivable {
            get {
                return ResourceManager.GetString("AccountsReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to накопичена амортизація.
        /// </summary>
        internal static string accumulatedDepreciation {
            get {
                return ResourceManager.GetString("accumulatedDepreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Накопичені курсові різниці.
        /// </summary>
        internal static string AccumulatedExchangeRateDifferences {
            get {
                return ResourceManager.GetString("AccumulatedExchangeRateDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатковий капітал.
        /// </summary>
        internal static string AdditionalCapital {
            get {
                return ResourceManager.GetString("AdditionalCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоригована середньорічна кількість простих акцій.
        /// </summary>
        internal static string AdjustedAverageNumberOrdinaryShares {
            get {
                return ResourceManager.GetString("AdjustedAverageNumberOrdinaryShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоригований чистий прибуток (збиток) на одну просту акцію.
        /// </summary>
        internal static string AdjustedNetProfitLossPerOrdinaryShare {
            get {
                return ResourceManager.GetString("AdjustedNetProfitLossPerOrdinaryShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адміністративні витрати.
        /// </summary>
        internal static string AdministrativeExpenses {
            get {
                return ResourceManager.GetString("AdministrativeExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амортизація.
        /// </summary>
        internal static string Amortization {
            get {
                return ResourceManager.GetString("Amortization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стаття.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцінка фінансової звітності.
        /// </summary>
        internal static string AssessmentOfFinancialStatements {
            get {
                return ResourceManager.GetString("AssessmentOfFinancialStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актив.
        /// </summary>
        internal static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На початок звітного періоду.
        /// </summary>
        internal static string AtBeginningReportingPeriod {
            get {
                return ResourceManager.GetString("AtBeginningReportingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на початок року.
        /// </summary>
        internal static string atBeginOfYear {
            get {
                return ResourceManager.GetString("atBeginOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На кінець звітного періоду.
        /// </summary>
        internal static string AtEndingReportingPeriod {
            get {
                return ResourceManager.GetString("AtEndingReportingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на кінець року.
        /// </summary>
        internal static string atEndOfYear {
            get {
                return ResourceManager.GetString("atEndOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середньорічна кількість простих акцій.
        /// </summary>
        internal static string AverageNumberOrdinaryShares {
            get {
                return ResourceManager.GetString("AverageNumberOrdinaryShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовий рік.
        /// </summary>
        internal static string BaseYear {
            get {
                return ResourceManager.GetString("BaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розрахунок показників прибутковості акцій.
        /// </summary>
        internal static string CalculationStockProfitabilityIndicators {
            get {
                return ResourceManager.GetString("CalculationStockProfitabilityIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Капітал у дооцінках.
        /// </summary>
        internal static string CapitalInRevaluations {
            get {
                return ResourceManager.GetString("CapitalInRevaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика капіталу.
        /// </summary>
        internal static string CharacteristicsOfCapital {
            get {
                return ResourceManager.GetString("CharacteristicsOfCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця {0}. Характеристика капіталу {1} за {2}-{3} роки.
        /// </summary>
        internal static string CharacteristicsOfCapitalTablName {
            get {
                return ResourceManager.GetString("CharacteristicsOfCapitalTablName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва компанії.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сукупний дохід.
        /// </summary>
        internal static string ComprehensiveIncome {
            get {
                return ResourceManager.GetString("ComprehensiveIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собівартість реалізованої продукції (товарів, робіт, послуг).
        /// </summary>
        internal static string CostOfGoodsSold {
            get {
                return ResourceManager.GetString("CostOfGoodsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточна кредиторська заборгованість за.
        /// </summary>
        internal static string CurrentAccountsPayableFor {
            get {
                return ResourceManager.GetString("CurrentAccountsPayableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оборотні активи.
        /// </summary>
        internal static string CurrentAssets {
            get {
                return ResourceManager.GetString("CurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточні біологічні активи.
        /// </summary>
        internal static string CurrentBiologicalAssets {
            get {
                return ResourceManager.GetString("CurrentBiologicalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточні фінансові інвестиції.
        /// </summary>
        internal static string CurrentFinancialInvestments {
            get {
                return ResourceManager.GetString("CurrentFinancialInvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточні зобов&apos;язання і забезпечення.
        /// </summary>
        internal static string CurrentLiabilitiesAndProvisions {
            get {
                return ResourceManager.GetString("CurrentLiabilitiesAndProvisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточні забезпечення.
        /// </summary>
        internal static string CurrentSupplies {
            get {
                return ResourceManager.GetString("CurrentSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточний рік.
        /// </summary>
        internal static string CurrentYear {
            get {
                return ResourceManager.GetString("CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відрахування на соціальні заходи.
        /// </summary>
        internal static string DeductionsSocialEvents {
            get {
                return ResourceManager.GetString("DeductionsSocialEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відстрочені податкові зобов&apos;язання.
        /// </summary>
        internal static string DeferredTaxLiabilities {
            get {
                return ResourceManager.GetString("DeferredTaxLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to відхилення.
        /// </summary>
        internal static string deviation {
            get {
                return ResourceManager.GetString("deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дивіденди на одну просту акцію.
        /// </summary>
        internal static string DividendsPerSimpleShare {
            get {
                return ResourceManager.GetString("DividendsPerSimpleShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Елементи операційних витрат.
        /// </summary>
        internal static string ElementsOperatingCosts {
            get {
                return ResourceManager.GetString("ElementsOperatingCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Власний капітал.
        /// </summary>
        internal static string Equity {
            get {
                return ResourceManager.GetString("Equity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрати (дохід) з податку на прибуток.
        /// </summary>
        internal static string ExpensesIncomeFromIncomeTax {
            get {
                return ResourceManager.GetString("ExpensesIncomeFromIncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінансові витрати.
        /// </summary>
        internal static string FinancialExpenses {
            get {
                return ResourceManager.GetString("FinancialExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінансовий результат до оподаткування.
        /// </summary>
        internal static string FinancialResultBeforeTax {
            get {
                return ResourceManager.GetString("FinancialResultBeforeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінансовий результат від операційної діяльності.
        /// </summary>
        internal static string FinancialResultFromOperatingActivities {
            get {
                return ResourceManager.GetString("FinancialResultFromOperatingActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінансові результати.
        /// </summary>
        internal static string FinancialResults {
            get {
                return ResourceManager.GetString("FinancialResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основні засоби.
        /// </summary>
        internal static string FixedAssets {
            get {
                return ResourceManager.GetString("FixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрати майбутніх періодів.
        /// </summary>
        internal static string FutureExpenses {
            get {
                return ResourceManager.GetString("FutureExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доходи майбутніх періодів.
        /// </summary>
        internal static string FutureIncome {
            get {
                return ResourceManager.GetString("FutureIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна інформація.
        /// </summary>
        internal static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to товари, роботи, послуги.
        /// </summary>
        internal static string goodsWorksServices {
            get {
                return ResourceManager.GetString("goodsWorksServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валовий.
        /// </summary>
        internal static string Gross {
            get {
                return ResourceManager.GetString("Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to темп роста.
        /// </summary>
        internal static string growthRate {
            get {
                return ResourceManager.GetString("growthRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to у тому числі з податку на прибуток.
        /// </summary>
        internal static string includingIncomeTax {
            get {
                return ResourceManager.GetString("includingIncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дохід від участі в капіталі.
        /// </summary>
        internal static string IncomeFromEquityParticipation {
            get {
                return ResourceManager.GetString("IncomeFromEquityParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Податок на прибуток, пов’язаний з іншим сукупним доходом.
        /// </summary>
        internal static string IncomeTaxRelatedOtherComprehensiveIncome {
            get {
                return ResourceManager.GetString("IncomeTaxRelatedOtherComprehensiveIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Незавершені капітальні інвестиції.
        /// </summary>
        internal static string IncompleteCapitalInvestments {
            get {
                return ResourceManager.GetString("IncompleteCapitalInvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показники.
        /// </summary>
        internal static string Indicators {
            get {
                return ResourceManager.GetString("Indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to первісна вартість.
        /// </summary>
        internal static string initialCost {
            get {
                return ResourceManager.GetString("initialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхідні дані.
        /// </summary>
        internal static string InputData {
            get {
                return ResourceManager.GetString("InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нематеріальні активи.
        /// </summary>
        internal static string IntangibleAssets {
            get {
                return ResourceManager.GetString("IntangibleAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інвестиційна нерухомість.
        /// </summary>
        internal static string InvestmentProperty {
            get {
                return ResourceManager.GetString("InvestmentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пасив.
        /// </summary>
        internal static string Liabilities {
            get {
                return ResourceManager.GetString("Liabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зобов&apos;язання, пов&apos;язані з необоротними активами утримуваними для продажу, та групами вибуття.
        /// </summary>
        internal static string LiabilitiesRelatedNonCurrentAssetsHeldForSale {
            get {
                return ResourceManager.GetString("LiabilitiesRelatedNonCurrentAssetsHeldForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код рядка.
        /// </summary>
        internal static string LineСode {
            get {
                return ResourceManager.GetString("LineСode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові кредити банків.
        /// </summary>
        internal static string LongTermBankCredits {
            get {
                return ResourceManager.GetString("LongTermBankCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові біологічні активи.
        /// </summary>
        internal static string LongTermBiologicalAssets {
            get {
                return ResourceManager.GetString("LongTermBiologicalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові фінансові інвестиції.
        /// </summary>
        internal static string LongTermFinancialIvestments {
            get {
                return ResourceManager.GetString("LongTermFinancialIvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to довгостроковими зобов&apos;язаннями.
        /// </summary>
        internal static string longTermLiabilities {
            get {
                return ResourceManager.GetString("longTermLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові зобов&apos;язання і забезпечення.
        /// </summary>
        internal static string LongTermLiabilitiesAndCollateral {
            get {
                return ResourceManager.GetString("LongTermLiabilitiesAndCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокові забезпечення.
        /// </summary>
        internal static string LongTermLoans {
            get {
                return ResourceManager.GetString("LongTermLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгострокова дебіторська заборгованість.
        /// </summary>
        internal static string LongTermReceivables {
            get {
                return ResourceManager.GetString("LongTermReceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to збиток.
        /// </summary>
        internal static string loss {
            get {
                return ResourceManager.GetString("loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Втрати від участі в капіталі.
        /// </summary>
        internal static string LossesFromEquityParticipation {
            get {
                return ResourceManager.GetString("LossesFromEquityParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матеріальні затрати.
        /// </summary>
        internal static string MaterialCosts {
            get {
                return ResourceManager.GetString("MaterialCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гроші та їх еквіваленти.
        /// </summary>
        internal static string MoneyAndTheirEquivalents {
            get {
                return ResourceManager.GetString("MoneyAndTheirEquivalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистий фінансовий результат.
        /// </summary>
        internal static string NetFinancialResult {
            get {
                return ResourceManager.GetString("NetFinancialResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистий дохід від реалізації продукції (товарів, робіт, послуг).
        /// </summary>
        internal static string NetIncomeFromSalesOfProducts {
            get {
                return ResourceManager.GetString("NetIncomeFromSalesOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистий прибуток (збиток) на одну просту акцію.
        /// </summary>
        internal static string NetProfitLossPerOrdinaryShare {
            get {
                return ResourceManager.GetString("NetProfitLossPerOrdinaryShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необоротні активи.
        /// </summary>
        internal static string NonCurrentAssets {
            get {
                return ResourceManager.GetString("NonCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необоротні активи, утримувані для продажу, та групи вибуття.
        /// </summary>
        internal static string NonCurrentAssetsHeldForSale {
            get {
                return ResourceManager.GetString("NonCurrentAssetsHeldForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № п/п.
        /// </summary>
        internal static string NumberInOrder {
            get {
                return ResourceManager.GetString("NumberInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за виданими авансами.
        /// </summary>
        internal static string onIssuedAdvances {
            get {
                return ResourceManager.GetString("onIssuedAdvances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other expenses.
        /// </summary>
        internal static string Other_expenses {
            get {
                return ResourceManager.GetString("Other expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інший сукупний дохід після оподаткування.
        /// </summary>
        internal static string OtherAggregateIncomeAfterTax {
            get {
                return ResourceManager.GetString("OtherAggregateIncomeAfterTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інший сукупний дохід до оподаткування.
        /// </summary>
        internal static string OtherAggregatePreTaxIncome {
            get {
                return ResourceManager.GetString("OtherAggregatePreTaxIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші оборотні активи.
        /// </summary>
        internal static string OtherCurrentAssets {
            get {
                return ResourceManager.GetString("OtherCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші поточні зобов&apos;язання.
        /// </summary>
        internal static string OtherCurrentLiabilities {
            get {
                return ResourceManager.GetString("OtherCurrentLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інша поточна дебіторська заборгованість.
        /// </summary>
        internal static string OtherCurrentReceivables {
            get {
                return ResourceManager.GetString("OtherCurrentReceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші витрати.
        /// </summary>
        internal static string OtherExpenses {
            get {
                return ResourceManager.GetString("OtherExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші фінансові доходи.
        /// </summary>
        internal static string OtherFinancialIncome {
            get {
                return ResourceManager.GetString("OtherFinancialIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to інші фінансові інвестиції.
        /// </summary>
        internal static string otherFinancialInvestments {
            get {
                return ResourceManager.GetString("otherFinancialInvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші необоротні активи.
        /// </summary>
        internal static string OtherFixedAssets {
            get {
                return ResourceManager.GetString("OtherFixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші доходи.
        /// </summary>
        internal static string OtherIncome {
            get {
                return ResourceManager.GetString("OtherIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші довгострокові зобов&apos;язання.
        /// </summary>
        internal static string OtherLongTermLiabilities {
            get {
                return ResourceManager.GetString("OtherLongTermLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші операційні витрати.
        /// </summary>
        internal static string OtherOperatingExpenses {
            get {
                return ResourceManager.GetString("OtherOperatingExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші операційні доходи.
        /// </summary>
        internal static string OtherOperatingIncome {
            get {
                return ResourceManager.GetString("OtherOperatingIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інший сукупний дохід.
        /// </summary>
        internal static string OtherTotalIncome {
            get {
                return ResourceManager.GetString("OtherTotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to прибуток.
        /// </summary>
        internal static string profit {
            get {
                return ResourceManager.GetString("profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибуток (збиток) від припиненої діяльності після оподаткування.
        /// </summary>
        internal static string ProfitLossFromDiscontinuedOperationsAfterTax {
            get {
                return ResourceManager.GetString("ProfitLossFromDiscontinuedOperationsAfterTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дебіторська заборгованість за продукцію, товари, роботи, послуги.
        /// </summary>
        internal static string ReceivablesForProducts {
            get {
                return ResourceManager.GetString("ReceivablesForProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєстрований (пайовий) капітал.
        /// </summary>
        internal static string RegisteredСapital {
            get {
                return ResourceManager.GetString("RegisteredСapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервний капітал.
        /// </summary>
        internal static string ReserveCapital {
            get {
                return ResourceManager.GetString("ReserveCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нерозподілений прибуток (непокритий збиток).
        /// </summary>
        internal static string RetainedEarnings {
            get {
                return ResourceManager.GetString("RetainedEarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дооцінка (уцінка) фінансових інструментів.
        /// </summary>
        internal static string RevaluationDepreciationFinancialInstruments {
            get {
                return ResourceManager.GetString("RevaluationDepreciationFinancialInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дооцінка (уцінка) необоротних активів.
        /// </summary>
        internal static string RevaluationDepreciationNonCurrentAssets {
            get {
                return ResourceManager.GetString("RevaluationDepreciationNonCurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрати на оплату праці.
        /// </summary>
        internal static string SalaryExpenses {
            get {
                return ResourceManager.GetString("SalaryExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти у файл.
        /// </summary>
        internal static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрати на збут.
        /// </summary>
        internal static string SellingExpenses {
            get {
                return ResourceManager.GetString("SellingExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to розрахунками з бюджетом.
        /// </summary>
        internal static string settlementsWithBudget {
            get {
                return ResourceManager.GetString("settlementsWithBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to розрахунками зі страхування.
        /// </summary>
        internal static string settlementsWithInsurance {
            get {
                return ResourceManager.GetString("settlementsWithInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to розрахунками з оплати праці.
        /// </summary>
        internal static string settlementsWithPayroll {
            get {
                return ResourceManager.GetString("settlementsWithPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частка іншого сукупного доходу асоційованих та спільних підприємств.
        /// </summary>
        internal static string ShareOtherComprehensiveIncome {
            get {
                return ResourceManager.GetString("ShareOtherComprehensiveIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткострокові кредити банків.
        /// </summary>
        internal static string ShortTermBankCredits {
            get {
                return ResourceManager.GetString("ShortTermBankCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звіт про фінансові результати (Звіт про сукупний дохід).
        /// </summary>
        internal static string StatementOfFinancialPerformance {
            get {
                return ResourceManager.GetString("StatementOfFinancialPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запаси.
        /// </summary>
        internal static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цільове фінансування.
        /// </summary>
        internal static string TargetedFinancing {
            get {
                return ResourceManager.GetString("TargetedFinancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тис.грн..
        /// </summary>
        internal static string thousandUAH {
            get {
                return ResourceManager.GetString("thousandUAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разом.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сукупний дохід.
        /// </summary>
        internal static string TotalIncome {
            get {
                return ResourceManager.GetString("TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усього за розділом.
        /// </summary>
        internal static string TotalSection {
            get {
                return ResourceManager.GetString("TotalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неоплачений капітал.
        /// </summary>
        internal static string UnpaidCapital {
            get {
                return ResourceManager.GetString("UnpaidCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити з файлу.
        /// </summary>
        internal static string UploadFromFile {
            get {
                return ResourceManager.GetString("UploadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to знос.
        /// </summary>
        internal static string wear {
            get {
                return ResourceManager.GetString("wear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to які обліковуються за методом участі в капіталі інших підприємств.
        /// </summary>
        internal static string whichAccountedForUsingEquityMethod {
            get {
                return ResourceManager.GetString("whichAccountedForUsingEquityMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to з бюджетом.
        /// </summary>
        internal static string withBudget {
            get {
                return ResourceManager.GetString("withBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вилучений капітал.
        /// </summary>
        internal static string WithdrawnCapital {
            get {
                return ResourceManager.GetString("WithdrawnCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рік.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
